import { config } from "dotenv";
config({ path: ".env.local" });

import { createClient } from "@supabase/supabase-js";
import Anthropic from "@anthropic-ai/sdk";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY!,
});

async function translateBatch(texts: string[], targetLang: string): Promise<string[]> {
  const langNames: Record<string, string> = { en: "English", ru: "Russian", ua: "Ukrainian" };

  const prompt = `Translate these Bulgarian HVAC technical terms to ${langNames[targetLang]}.
Keep brand names, model numbers, units (kW, BTU, dB, mm, кг, °C) unchanged.
Return ONLY a JSON array of translated strings, same order. No explanations.

${JSON.stringify(texts)}`;

  const response = await anthropic.messages.create({
    model: "claude-opus-4-6",
    max_tokens: 4096,
    messages: [{ role: "user", content: prompt }],
  });

  const block = response.content[0];
  if (block.type === "text") {
    try {
      return JSON.parse(block.text);
    } catch {
      console.error("Failed to parse:", block.text.slice(0, 200));
      return texts; // fallback to originals
    }
  }
  return texts;
}

async function main() {
  console.log("=== AI Feature Translation (Opus) ===\n");

  // 1. Collect ALL unique feature names from all products
  console.log("1. Collecting unique feature names...");
  const { data: products } = await supabase
    .from("products")
    .select("features")
    .eq("is_active", true)
    .not("features", "is", null);

  const uniqueNames = new Set<string>();
  const uniqueSections = new Set<string>();

  for (const product of products || []) {
    const features = product.features;
    if (!features || typeof features !== "object") continue;
    for (const [, group] of Object.entries(features as Record<string, { name: string; items: Array<{ name: string; value: string }> }>)) {
      uniqueSections.add(group.name);
      for (const item of group.items || []) {
        uniqueNames.add(item.name);
      }
    }
  }

  console.log(`   Found ${uniqueNames.size} unique feature names`);
  console.log(`   Found ${uniqueSections.size} unique section names`);

  // 2. Collect all unique category group names
  const { data: categories } = await supabase
    .from("categories")
    .select("group_name")
    .order("group_name");

  const uniqueGroupNames = new Set<string>();
  for (const cat of categories || []) {
    uniqueGroupNames.add(cat.group_name);
  }
  console.log(`   Found ${uniqueGroupNames.size} unique category groups\n`);

  // 3. Translate everything in batches
  const allTexts = [
    ...Array.from(uniqueSections),
    ...Array.from(uniqueNames),
    ...Array.from(uniqueGroupNames),
  ];

  console.log(`2. Translating ${allTexts.length} terms to 3 languages via Opus...\n`);

  const translations: Record<string, Record<string, string>> = {};

  for (const lang of ["en", "ru", "ua"] as const) {
    console.log(`   Translating to ${lang}...`);

    // Batch in groups of 30
    const batchSize = 30;
    const results: string[] = [];

    for (let i = 0; i < allTexts.length; i += batchSize) {
      const batch = allTexts.slice(i, i + batchSize);
      const translated = await translateBatch(batch, lang);
      results.push(...translated);
      process.stdout.write(`     ${Math.min(i + batchSize, allTexts.length)}/${allTexts.length}\r`);
      await new Promise((r) => setTimeout(r, 300));
    }

    console.log(`   ✓ ${lang}: ${results.length} terms translated`);

    for (let i = 0; i < allTexts.length; i++) {
      if (!translations[allTexts[i]]) translations[allTexts[i]] = {};
      translations[allTexts[i]][lang] = results[i];
    }
  }

  // 4. Write the translation map as a TypeScript file
  console.log("\n3. Writing translation map...");

  let output = `// Auto-generated by translate-features-ai.ts using Claude Opus\n`;
  output += `// ${new Date().toISOString()}\n\n`;
  output += `export const featureTranslationsAI: Record<string, { en: string; ru: string; ua: string }> = {\n`;

  for (const [bg, tr] of Object.entries(translations)) {
    const en = (tr.en || bg).replace(/"/g, '\\"');
    const ru = (tr.ru || bg).replace(/"/g, '\\"');
    const ua = (tr.ua || bg).replace(/"/g, '\\"');
    output += `  "${bg.replace(/"/g, '\\"')}": { en: "${en}", ru: "${ru}", ua: "${ua}" },\n`;
  }

  output += `};\n\n`;
  output += `export function translateFeatureAI(bgText: string, locale: string): string {\n`;
  output += `  if (locale === "bg") return bgText;\n`;
  output += `  const tr = featureTranslationsAI[bgText];\n`;
  output += `  if (tr) return tr[locale as "en" | "ru" | "ua"] || bgText;\n`;
  output += `  // Partial match\n`;
  output += `  for (const [key, val] of Object.entries(featureTranslationsAI)) {\n`;
  output += `    if (bgText.includes(key) || key.includes(bgText)) return val[locale as "en" | "ru" | "ua"] || bgText;\n`;
  output += `  }\n`;
  output += `  return bgText;\n`;
  output += `}\n`;

  const fs = await import("fs");
  fs.writeFileSync(
    "/Users/oleksandr/Desktop/Proects DANGROW /pesnopoets.clima/lib/i18n/feature-translations-ai.ts",
    output
  );

  // 5. Also update category group names in DB
  console.log("\n4. Updating category group translations in DB...");

  // Add group_name translations — we'll store them in a mapping and apply via sidebar
  const groupTranslations: Record<string, { en: string; ru: string; ua: string }> = {};
  const groupNames = Array.from(uniqueGroupNames);

  for (let i = 0; i < groupNames.length; i++) {
    const bg = groupNames[i];
    groupTranslations[bg] = {
      en: translations[bg]?.en || bg,
      ru: translations[bg]?.ru || bg,
      ua: translations[bg]?.ua || bg,
    };
  }

  // Write group translations to the same file
  let groupOutput = fs.readFileSync(
    "/Users/oleksandr/Desktop/Proects DANGROW /pesnopoets.clima/lib/i18n/feature-translations-ai.ts",
    "utf-8"
  );
  groupOutput += `\nexport const categoryGroupTranslations: Record<string, { en: string; ru: string; ua: string }> = {\n`;
  for (const [bg, tr] of Object.entries(groupTranslations)) {
    groupOutput += `  "${bg.replace(/"/g, '\\"')}": { en: "${tr.en.replace(/"/g, '\\"')}", ru: "${tr.ru.replace(/"/g, '\\"')}", ua: "${tr.ua.replace(/"/g, '\\"')}" },\n`;
  }
  groupOutput += `};\n\n`;
  groupOutput += `export function translateGroupName(bgName: string, locale: string): string {\n`;
  groupOutput += `  if (locale === "bg") return bgName;\n`;
  groupOutput += `  return categoryGroupTranslations[bgName]?.[locale as "en" | "ru" | "ua"] || bgName;\n`;
  groupOutput += `}\n`;

  fs.writeFileSync(
    "/Users/oleksandr/Desktop/Proects DANGROW /pesnopoets.clima/lib/i18n/feature-translations-ai.ts",
    groupOutput
  );

  console.log("\n=== Done! ===");
  console.log(`Total terms: ${allTexts.length}`);
  console.log(`Output: lib/i18n/feature-translations-ai.ts`);
}

main().catch(console.error);
